spring:
  profiles:
    active: test
  application:
    name: service-user

server:
  port: 8100

# 开启feign
feign:
  sentinel:
    enabled: true

# 用于nacos的健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 用于mybatis检测
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml


